version: '3.4'

services:
  biz.brightonion.identityservice:
    image: ${DOCKER_REGISTRY-}bizbrightonionidentityservice
    build:
      context: .
      dockerfile: Services/Identity/Biz.BrightOnion.Identity.API/Dockerfile

  biz.brightonion.orderingservice:
    image: ${DOCKER_REGISTRY-}bizbrightonionorderingservice
    build:
      context: .
      dockerfile: Services/Ordering/Biz.BrightOnion.Ordering.API/Dockerfile

