version: '3.4'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: brightonion_sql

  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: brightonion_rabbit
    hostname: brightonion_rabbit

  jaeger:
    image: jaegertracing/all-in-one
    container_name: brightonion_jaeger

  consul:
    image: consul
    container_name: brightonion_consul

  web:
    image: ${DOCKER_REGISTRY-}brightonion_web
    build:
      context: .
      dockerfile: Web/frontend/Dockerfile

  api_gateway:
    image: ${DOCKER_REGISTRY-}brightonion_api_gateway
    build:
      context: .
      dockerfile: ApiGateways/Biz.BrightOnion.ApiGateway/Dockerfile

  ordering_aggregator:
    image: ${DOCKER_REGISTRY-}brightonion_ordering_aggregator
    build:
      context: .
      dockerfile: ApiGateways/Ordering/Biz.BrightOnion.ApiGateway.OrderingAggregator/Dockerfile

  identity_api:
    image: ${DOCKER_REGISTRY-}brightonion_identity_api
    build:
      context: .
      dockerfile: Services/Identity/Biz.BrightOnion.Identity.API/Dockerfile
    depends_on:
      - sql
      - consul

  identity_bgt:
    image: ${DOCKER_REGISTRY-}brightonion_identity_bgt
    build:
      context: .
      dockerfile: Services/Identity/Biz.BrightOnion.Identity.BackgroundTasks/Dockerfile
    depends_on:
      - sql
      - rabbit

  rooms_api:
    image: ${DOCKER_REGISTRY-}brightonion_rooms_api
    build:
      context: .
      dockerfile: Services/Rooms/Biz.BrightOnion.Rooms.API/Dockerfile
    depends_on:
      - sql
      - consul

  rooms_bgt:
    image: ${DOCKER_REGISTRY-}brightonion_rooms_bgt
    build:
      context: .
      dockerfile: Services/Rooms/Biz.BrightOnion.Rooms.BackgroundTasks/Dockerfile
    depends_on:
      - sql
      - rabbit

  order_api:
    image: ${DOCKER_REGISTRY-}brightonion_order_api
    build:
      context: .
      dockerfile: Services/Ordering/Biz.BrightOnion.Ordering.API/Dockerfile
    depends_on:
      - sql
      - rabbit
      - consul

  order_hub:
    image: ${DOCKER_REGISTRY-}brightonion_order_hub
    build:
      context: .
      dockerfile: Services/Ordering/Biz.BrightOnion.Ordering.SignalrHub/Dockerfile
    depends_on:
      - rabbit

#  analytics_api:
#    image: ${DOCKER_REGISTRY-}brightonion_analytics_api
#    build:
#      context: .
#      dockerfile: Services/Analytics/Biz.BrightOnion.Analytics.API/Dockerfile
